version: '3.7'
services:
  myapp:
    image: fergus98/flaskapp:v1
    build: .
    ports:
    - target: 5000
      published: 5000
    deploy:
      replicas: 4
    depends_on:
    - mysql
    environment:
    - DATABASE_URI=mysql+pymysql://root:password@mysql/baseball
    - SECRET_KEY=jhgfghj
  mysql:
    image: fergus98/flaskdb:v1
    environment:
    - MYSQL_ROOT_PASSWORD=password
    volumes:
    - type: volume
      source: sqlvol
      target: /var/lib/mysql
volumes:
 sqlvol:

