version: '3.7'
services:
  myapp:
    image: fergus98/verse_gapminder
    build: .
    networks:
    - testnet
    ports:
    - target: 5000
      published: 5000
    depends_on:
    - mysql
    environment:
    - DATABASE_URI=mysql+pymysql://root:password@mysql/baseball
    - SECRET_KEY=jhgfghj
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks: 
    - testnet
    ports:
    - target: 3306
      published: 3306
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=baseball
    volumes:
    - type: volume
      source: sqlvol
      target: /var/lib/mysql
networks:
 testnet:
volumes:
 sqlvol:

