version: '3.7'
services:
  myapp:
    image: fergus98/flaskapp:v1
    build: .
    deploy:
      replicas: 4
    depends_on:
    - mysql
    environment:
    - DATABASE_URI=mysql+pymysql://root:password@mysql/baseball
    - SECRET_KEY=jhgfghj
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - myapp  
  mysql:
    image: fergus98/flaskdb:v1
    environment:
    - MYSQL_ROOT_PASSWORD=password
    volumes:
    - type: volume
      source: sqlvol
      target: /var/lib/mysql
volumes:
 sqlvol:

